<?php
/**
 * Created by PhpStorm.
 * User: 魏巍 jswei30@gmail.com
 * Date: 2016/10/11
 * Time: 16:57
 **/

namespace Home\Controller;
use Think\Controller;

class NewsController extends BaseController{
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->current = session('now_nav_first');
    }
    public function index(){
		
        $id=$this->current['name'];
        $id = M('column')->field('id,title')->where(array('name'=>$id))->find();
        $map['column_id']=$id['id'];
        switch ($this->current['type']){
            case 1:
            case 2:
                $order = 'sort asc,create_time desc';
                $list = $this->getlist(M('article'),$map,$order,'');
                $this->list = $list;
                break;
            case 3:
                $this->list  = $list =  M('article')->field('id,content')->where($map)->find();
                break;
        }
        $this->carousel = $this->get_site_carousel();
        $this->display($this->tpl);
    }
    
    public function detail($aid=0){
        if($aid){
            $m = D('Article');
            $detail = $m->field('gid',true)->find($aid);
            $m->set_hits($detail['id']);
            $this->prev = $prev = $m->get_pre($detail['id'],$detail['column_id']);
            $this->next =$next = $m->get_next($detail['id'],$detail['column_id']);
            $c = $m->get_colunm($detail['column_id']);
            $detail['column'] = $c['title'];
            $this->vo=$detail;
            $this->display('details');
        }
        
    }
    /**
     * 获取分页数据
     * @param type $model模型名(默认获取当前model)
     * @param type $map条件
     * @param type $order排序
     * @param type $field需要查询的字段，默认全部
     * @param type $pagination为每页显示的数量，默认为配置中的值
     * @return type返回结果数组
     */
    protected function getlist($model = '', $map = '', $order = '',$group = '', $pagination = '', $field = '*') {

        $model=!empty($model)?$model:M(CONTROLLER_NAME);
        $count = $model->where($map)->cache(true)->group($group)->count('*');
        $pagination = $pagination ? $pagination : C('PAGE_SIZE');

        $p = new \Think\Page($count, $pagination,array('url'=>'/',$_GET['id']?$_GET['id']:''),'_');
        $p->setConfig('header', '<a class="rows">当前 %NOW_PAGE%/%TOTAL_PAGE%页</a>');
        $p->setConfig('prev', '上一页');
        $p->setConfig('next','下一页');
        $p->setConfig('last', '最后一页');
        $p->setConfig('first','第一页');
        $p->setConfig('theme', '%UP_PAGE%%HEADER%%DOWN_PAGE%');
        $p->allShow = 1;
        $show=$p->show();
        $this->assign('page', $show);
        $res = $model->where($map)->cache(true)->field($field)->group($group)->limit($p->firstRow . ',' . $p->listRows)->order($order)->select();

        return $res;
    }
}